const STATIC_AXIS_MIN = -1.5;
const STATIC_AXIS_MAX = 10.5;
const RANGE_EQN_START_VALUE = 0;
const SCALE_FACTOR_DEFAULT = 1;
const ROUNDING_DECIMAL_POINTS = 1;
const OVERLAP_TOLERANCE = 1;

const ASPECT_RATIO = 16/9;
const TICKMARK_HEIGHT = 5;
